### ISSUE TITLE
[feature] feed preview

### ISSUE THREAD

**Issue by atomGit** [igorlogius/detect-feeds#1]
you have any thoughts on providing a rudimentary feed preview function? might be nice to re-add the functionality that the 'geniuses' at Moz removed

**Comment by igorlogius** [comment]
Adding that feature would require requsting and parsing feeds, which to be fair ... isn't fun.
If i find a good library for this, i might consider it. 
You can leave this issue open and i'll come back to it when i have a little more time on my hands.

**Comment by igorlogius** [comment]
This could be useful  
https://github.com/fent/feedme.js

**Comment by igorlogius** [comment]
Since i dont seem to find good answers to the "Open Questions" i decided to not add the feed preview feature. 
It would simply destory the "minimalistic" aspect and most likely at the beginning work badly.

So i'll be closing this issue, but i might create a seperate addon to display feeds in the (nearish) future.
